FROM mhart/alpine-node:14.16.0 as build-step

WORKDIR /client

ENV PATH="./node_modules/.bin:$PATH"

COPY package.json /client
COPY yarn.lock /client
RUN yarn
COPY . ./client
RUN yarn build

CMD ["npm", "run", "server"]