version: '3'

services:
  client:
    image: nurruty/rick-morty-client:dev
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./client:/client
      - /client/node_modules
    environment:
      - JWT_SECRET=testSecret
      - DB_ENV=testing
      - COOKIE_EXPIRATION=620000
    links:
      - api
    networks:
      - webappnetwork
  api:
    image: nurruty/rick-morty-api:dev
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - ./api:/api
      - /api/node_modules
    environment:
      - DATABASE_URL=mongodb://mongo:27017/test
    depends_on:
      - mongo
    networks:
      - webappnetwork
  mongo-seed:
    image: fvilers/mongo-seed
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - ./api/data:/api/data
    command: 'mongoimport --host mongo --port 27017 --db test --collection users --mode upsert --type json --file /api/data/init.json --jsonArray'
    networks:
      - webappnetwork
  mongo:
    image: mongo:3.4
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
