const GET_USER_API_PATH = '';
const LOGIN_USER_PATH = '';

const GET_CHARACTERS_API_PATH = '';
const GET_CHARACTER_API_PATH = '';
const ADD_FAVOURITE_CHARACTER_API_PATH = '';
const DELETE_FAVOURITE_CHARACTER_API_PATH = '';

export {
  GET_USER_API_PATH,
  LOGIN_USER_PATH,
  GET_CHARACTERS_API_PATH,
  GET_CHARACTER_API_PATH,
  ADD_FAVOURITE_CHARACTER_API_PATH,
  DELETE_FAVOURITE_CHARACTER_API_PATH,
};
