const GET_USER_API_PATH = '';
const LOGIN_USER_PATH = '';
const SIGNUP_USER_PATH = '';
const UPDATE_FAVOURITE_CHARACTER = '';

export { GET_USER_API_PATH, LOGIN_USER_PATH, SIGNUP_USER_PATH, UPDATE_FAVOURITE_CHARACTER };
