FROM mhart/alpine-node:14.16.0

WORKDIR /api

ENV PATH /api/node_modules/.bin:$PATH

COPY package.json /api/
COPY yarn.lock /api/

RUN yarn install --production

COPY . /api/

EXPOSE 80

CMD ["npm", "start"]